### ISSUE TITLE
R-builds deployment failing

### ISSUE THREAD

**Issue by glin** [rstudio/r-builds#165]
Looks like the deploy job started failing yesterday, but no obvious reason in the error messages. This should be fixed asap since we have some changes to deploy for R 4.3.0 tomorrow.

```sh
[2023-04-19T18:37:26.606Z] Error: `docker run --rm -v .cache/serverless-python-requirements/2b10c0467f75bfbcf12e9b77be65ec7563b90c5995f0eaa96faefbd42c337bdd_x86_64_slspyc:/var/task:z -v .cache/serverless-python-requirements/downloadCacheslspyc:/var/useDownloadCache:z lambci/lambda:build-python3.8 /bin/sh -c chown -R 0\:0 /var/useDownloadCache && python3.8 -m pip install -t /var/task/ -r /var/task/requirements.txt --cache-dir /var/useDownloadCache && chown -R 386\:386 /var/task && chown -R 386\:386 /var/useDownloadCache` Exited with code 125
[2023-04-19T18:37:26.606Z]     at ChildProcess.<anonymous> (/var/lib/jenkins/workspace/r-builds/deploy-r-builds/node_modules/child-process-ext/spawn.js:38:8)
[2023-04-19T18:37:26.606Z]     at ChildProcess.emit (events.js:400:28)
[2023-04-19T18:37:26.606Z]     at ChildProcess.emit (domain.js:475:12)
[2023-04-19T18:37:26.606Z]     at maybeClose (internal/child_process.js:1088:16)
[2023-04-19T18:37:26.606Z]     at Socket.<anonymous> (internal/child_process.js:446:11)
[2023-04-19T18:37:26.606Z]     at Socket.emit (events.js:400:28)
[2023-04-19T18:37:26.606Z]     at Socket.emit (domain.js:475:12)
[2023-04-19T18:37:26.606Z]     at Pipe.<anonymous> (net.js:686:12)
[2023-04-19T18:37:26.606Z] 
[2023-04-19T18:37:26.606Z] 2 deprecations found: run 'serverless doctor' for more details
[2023-04-19T18:37:26.606Z] make: *** [Makefile:40: serverless-deploy.staging] Error 1
```

**Comment by glin** [comment]
The issue appears to be with running Docker in Docker on Jenkins, for the serverless-python-requirements plugin, and actually started failing since February apparently. But it's also not as urgent as I thought originally, as the R 4.3 fixes were only in the Docker images and didn't need a deployment. I've confirmed that the published R 4.3 builds have the fixes already.

**Comment by glin** [comment]
This is no longer needed.
